### PR TITLE
Fix 4 Xcode implicit conversion warnings

### PR DESCRIPTION
**Pull request by stanislaw**
Hello,

It would be nice to have MagicKit 0.0.2 release which could be compiled with no warnings. 

Thanks.

### CODE REVIEW

**Comment by stanislaw** [comment]
Any updates?

**Comment by aelam** [comment]
Sorry ,very busy these days 
I will update it soon
Thank you .

**Comment by stanislaw** [comment]
No rush! Just wanted to make sure this is accepted.

MagicKit is the only one which produces warnings in our application while it is a rule for us to always make projects compile with 0 warnings.

Thanks for the answer.

**Comment by stanislaw** [comment]
ping... :smile:

**Comment by stanislaw** [comment]
Hm, strange... please see both [header](https://github.com/stanislaw/MagicKit/blob/master/libmagic/file.c#L129) and [function](https://github.com/stanislaw/MagicKit/blob/master/libmagic/file.c#L416) code. They seem to be identical. Am I missing something?

**Comment by stanislaw** [comment]
How do you obtain this compile error?

When I do "Run" of MagicKit framework inside Xcode - I don't see any warnings. I did see them when I cloned your fork for the first time, but now it runs with no errors/warnings after I've made these changes.

**Comment by aelam** [comment]
the OS X target is fine. 
But the iOS target has errors about size_t 
I will see it late 

发自我的 iPhone

**Comment by stanislaw** [comment]
Actually, when running iOS target I did see some other errors related to some functions derived from BSD which are now present in system libs. These errors were present before I did my fixes, that is why I didn't touch them in any way and fixed the warnings of this issue against the "MagicKitFramework" target.

I.e. iOS target has some other problems besides this one you mention which I myself have not seen.

**Pull request closed without merging**
